version: '3'
services: 
  springboot-testcontainer:
    image: springboot-testcontainer
   # env_file: ./environment.env
    environment: 
     - MYSQL_ROOT_PASSWORD=tooroottest
     - MYSQL_DATABASE=testcontainerdb
     - MYSQLDB_LOCAL_PORT=3306
     - MYSQLDB_DOCKER_PORT=3306
     - SPRING_LOCAL_PORT=8888
     - SPRING_DOCKER_PORT=8888
     - DB_HOST_NAME=mysqldb
    depends_on:
      - mysqldb
    #restart: always
    build: . # use command docker compose up --build to build the image
             #(build: . means it will use docker file available in current dir)
    ports:
      - 8888:8888
  mysqldb:
   #container-name: mydbcontainer
   image: mysql
   #env_file: ./environment.env
   volumes:
     - ./dbvolume:/var/lib/mysql
   ports:
    - 3306:3306
   environment:
     - MYSQL_ROOT_PASSWORD=tooroottest
     - MYSQL_DATABASE=testcontainerdb
     - MYSQLDB_LOCAL_PORT=3306
     - MYSQLDB_DOCKER_PORT=3306
     - SPRING_LOCAL_PORT=8888
     - SPRING_DOCKER_PORT=8888
     - DB_HOST_NAME=mysqldb
   