
server:
  port: 8787
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/graphqltest
    username: root
    password: root
    
    
  graphql:
    graphiql:
      enabled: true
    cors:
      allowed-origins: "*"
      