
server:
  port: 8787
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://${DB_HOST_NAME:localhost}:${MYSQLDB_LOCAL_PORT:3306}/${MYSQL_DATABASE:test}
    username: root
    password: ${MYSQL_ROOT_PASSWORD:root}
  graphql:
    graphiql:
      enabled: true
    cors:
      allowed-origins: "*"
      